### PR TITLE
FEATURE: Append

### PR DESCRIPTION
**Pull request by benpate**
This adds an `append` command to hyperscript that concatenates new values onto the end of a string, array, or HTMLElement's innerHTML.

```hyperscript
append "name" to myString -- adds "name" to the end of the string variable
append "name" to myArray -- .push() "name" as a new value in the array
append "string" to DOMNode -- sets innerHTML
append "string" -- appends value to the default "result" variable 
```

This makes a lot of new operations easy.  This code populates a DIV with a custom widget contents loaded from a remote service.

```hyperscript
def MyWidget(el, records)
    append "<table>"
    repeat for record in records
        append `<tr><td>${record.name}</td><td>${record.value}</td></tr>`
    end
    append "</table>
    put it into me
end

<div script="init fetch /mydata as JSON then call MyWidget(me, it)"></div>
```

### CODE REVIEW

**Comment by benpate** [comment]
I used the `put` and `set` commands as a model for this, but I'm not 100% confident in what I've done.  In particular, I'm not sure I'm handling the `target.type == "propertyAccess"` situation correctly, and I made a test that updated a DOM Node's ID, but it did not work right.  That may be an area to grow into later.  

Once the broad strokes of this command have been *blessed* I'm happy to write documentation.

**Comment by 1cg** [comment]
Looks reasonable.  Would be nice if it worked w/ strings too:
```
  append "foo" to myStr
```
That's a bit more work, would you be willing to take a crack at it?

**Comment by benpate** [comment]
It *should* work with strings. I'll double check and resubmit.

**Comment by 1cg** [comment]
Ah, I missed that!  Sorry! Looks great, just needs docs.  I'll accept this for now....

**Pull request merged**
