### PR TITLE
Fix 209: ElementCollection breaks some comparison functionality

### PR DESCRIPTION
**Pull request by 1cg**
This is a fix for https://github.com/bigskysoftware/_hyperscript/issues/209

I think it needs to be implemented for TemplatedQueryElementCollection as well.  @dz4k, thoughts?

### CODE REVIEW

**Comment by dz4k** [comment]
TemplatedQueryElementCollection _should_just inherit it... Maybe add a test with interpolation and see if it works? Off to class rn, will come back with more details

**Comment by 1cg** [comment]
Yeah, my concern is that I see you are adding attributes in the `css()` function and then removing them on iteration, so we'd be adding the attributes and not removing them I think?

Not sure if it matters.

**Comment by dz4k** [comment]
```js
		selectMatches() {
			this.elements.forEach((el, i) => el.dataset.hsQueryId = i);
			const rv = super.selectMatches();
			this.elements.forEach(el => el.removeAttribute('data-hs-query-id'));
			return rv;
		}
```

Removing `[Symbol.iterator]()` from TQEC and adding the above should do it.

**Comment by ajusa** [comment]
Quick question: Would it be possible to do something like `if .class` to check if there are any elements of .class? Does this PR account for that? Similarly, `if not .class` and `if no .class` should check if there are no elements of .class. I'm not sure if hyperscript used to do this, but if it didn't I think that'd be easier than writing out `if .class is not empty` all the time.

**Comment by 1cg** [comment]
`if no .class` should work

**Pull request merged**
