### PR TITLE
JSDoc: Additional progress

### PR DESCRIPTION
**Pull request by benpate**
More comments.  

- One tiny code change on line 3864 to include an obviously missing parameter from a public API call.
- Two small syntactically identical code changes on lines 1356 and 1488 to reference custom properties in events more correctly

### CODE REVIEW

**Comment by 1cg** [comment]
Do you mind pulling the latest and merging in your changes with it to resubmit?

**Comment by benpate** [comment]
on it.

**Comment by benpate** [comment]
Done.  I backed out my change to line 3890.  But, please take a look at it.  It seems like `_parser.addIndirectExpression` should take two variables, but we're currently only passing in one.

**Comment by 1cg** [comment]
yep, that was a bug!  Thankfully no usages of `addIndirectExpression` yet!

**Pull request merged**
