### PR TITLE
Redesign landing page

### PR DESCRIPTION
**Pull request by dz4k**
resim

resim

### CODE REVIEW

**Comment by 1cg** [comment]
One request: can you put the install URL centered in a div w/ a border & light backjgournd and some depth to it?

image

**Comment by 1cg** [comment]
probably worth centering this too:
image

**Comment by 1cg** [comment]
Some CSS maybe as a starting point
image

**Comment by dz4k** [comment]
The installation URL is a bit too prominent for my liking, considering that almost nobody will read it.

**Comment by 1cg** [comment]
maybe just a title then?

**Comment by 1cg** [comment]
or maybe just a "copy CDN" button, to get rid of the ugly url?

**Comment by dz4k** [comment]
WDYT?

resim

**Comment by 1cg** [comment]
much better.  only feedback is more vertical whitespace if you are OK w/ it

**Comment by dz4k** [comment]
resim

**Pull request merged**
