### PR TITLE
Fix "pick" command requiring identifier

### PR DESCRIPTION
**Pull request by TotallyGamerJet**
`Pick match/matches` requires that an identifier be present not the literal token `identifier`

### CODE REVIEW

**Comment by 1cg** [comment]
can you add a test for this?  Thank you!

**Comment by 1cg** [comment]
pinging again regarding at test on this PR, would love to integrate it!

**Comment by TotallyGamerJet** [comment]
Hey thanks for reaching out. I've been quite busy but when I get some time I'll see about adding tests

**Comment by 1cg** [comment]
simple enough and obviously the right fix, merging

**Pull request merged**
