### PR TITLE
Add `tailwindcss` show / hide strategies

### PR DESCRIPTION
**Pull request by juchom**
Following the discussion on discord, these strategies will add or remove the associated css class from tailwindcss.

### CODE REVIEW

**Comment by 1cg** [comment]
I'd like to make this an extension to hyperscript, rather than the core.  Are you OK with that?

We would need to add HIDE_SHOW_STRATEGIES to _hyperscript.config so you can add to it externally.

Are you OK w/ that idea?  Moving this to something like tailwinds_ext.js?

**Comment by juchom** [comment]
> I'd like to make this an extension to hyperscript, rather than the core. Are you OK with that?

You're the boss, you tell me what to do 😄 

And actually it makes sense 👍 

> Are you OK w/ that idea? Moving this to something like tailwinds_ext.js?

Where am I supposed to create this file `lib/plugin` or `lib/extensions` or somewhere else ?

**Comment by 1cg** [comment]
If you don't mind waiting a week, we are going to do some restructuring and can look at how things shake out after that.

**Comment by 1cg** [comment]
OK, yeesh, finally getting back to this.

So here is what I'd like to do: can you create a new extension in the `/src/ext/` directory (doesn't currently exist):

`/src/ext/tailwinds.js`

In that file, you can add in these transitions with the following code:

```js
_hyperscript.config.hideShowStrategies.twVisibility = function (op, element, arg) {
			if (op === "toggle") {
				if (element.classList.contains("invisible")) {
					HIDE_SHOW_STRATEGIES.tailwindcss("show", element, arg);
				} else {
					HIDE_SHOW_STRATEGIES.tailwindcss("hide", element, arg);
				}
			} else if (op === "hide") {
				element.classList.add('invisible');
			} else {
				element.classList.remove('invisible');
			}
		}
```

You'll need the latest code from dev, where I init `_hyperscript.config.hideShowStrategies` properly. 

We can use this file as a basis for a bunch of tailwinds-specific stuff for hyperscript.

**Comment by juchom** [comment]
Where do you want to have the tests for the strategies ?

**Comment by 1cg** [comment]
I vote `/test/ext/tailwinds.js`

Does that sound reasonable?

**Comment by juchom** [comment]
I've added the tests like this one but they all fail.

```js
describe("tailwindcss extensions", function () {
    beforeEach(function () {
		clearWorkArea();
	});
	afterEach(function () {
		clearWorkArea();
        _hyperscript.config.defaultHideShowStrategy = null;
	});

    it("can hide element, with tailwindcss hidden class", function () {
        _hyperscript.config.defaultHideShowStrategy = _hyperscript.config.hideShowStrategies.twDisplay;
		var div = make("<div _='on click hide'></div>");
		div.classList.contains("hidden").should.equal(false);
		div.click();
		div.classList.contains("hidden").should.equal(true);
	});
});
```

The function to test is this one :

```js
_hyperscript.config.hideShowStrategies.twDisplay = function (op, element, arg) {
    if (op === "toggle") {
        if (element.classList.contains("hidden")) {
            _hyperscript.config.hideShowStrategies.twDisplay("show", element, arg);
        } else {
            _hyperscript.config.hideShowStrategies.twDisplay("hide", element, arg);
        }
    } else if (op === "hide") {
        element.classList.add('hidden');
    } else {
        element.classList.remove('hidden');
    }
}
```

I'm missing something, but I don't get what...

**Comment by 1cg** [comment]
heya @juchom I want to take a look at this PR again.  Are you good w/ resurrecting it?

**Comment by juchom** [comment]
Ok, tell me what to do

**Comment by 1cg** [comment]
lmao this is now the oldest PR against hyperscript, but I do want to merge it during hyperscriptober

It looks like it needs some docs to me, how is it otherwise?

**Comment by juchom** [comment]
Crap... I wasn't expecting a force push...

**Comment by juchom** [comment]
I added everything back. But the force push was a mistake.

I'm not sure if we should keep this PR open, or if you want me to open a new one ?

**Comment by juchom** [comment]
Ok, I think I completly fucked up this PR while syncing my repo with the github ui. I can't find a way to properly fix this.

Is it ok for you if I reopen a new PR ?

**Comment by 1cg** [comment]
Of course. Sorry for the additional work!

**Pull request closed without merging**
