### PR TITLE
Make hyperscript more minifiable

### PR DESCRIPTION
**Pull request by dz4k**
Results
-------

| Bytes                 | Minified | Minified & Gzipped |
|:---------------|----------:|---------------------:|
| Current               |    72003 |   18316 |
| Optimized  |    71155 |   18298 |
| Diff. | 848 | 18 |

was this worth the effort?

### CODE REVIEW

**Comment by benpate** [comment]
This is wild and counterintuitive.  Yes.  I think it was worth the effort -- even if we don't get a big bump out of it.  The real-world examples are very valuable.

It seems like minification is one thing, but gzip is another.  Improving minification looks like it makes gzip harder or less effective.  Yes?  

We should probably strive for 1) clean code that 2) reduced obvious redundancies and inefficiencies, then 3) let the tools do their magic from there.  Does anyone know of any automated tools that can help us to identify/correct obviously inefficient code?

**Comment by dz4k** [comment]
@benpate,

> It seems like minification is one thing, but gzip is another. Improving minification looks like it makes gzip harder or less effective. Yes?

Yep, from my understanding, texxt compression relies on repetition.

> We should probably strive for 1) clean code that 2) reduced obvious redundancies and inefficiencies, then 3) let the tools do their magic from there. Does anyone know of any automated tools that can help us to identify/correct obviously inefficient code?

The main guideline is to use fewer object properties and methods, because objects are too dynamic to statically analyze. We might want to have the lexer/parser/runtime methods (within the core) as bare functions (instead of doing what I've done & making wrappers around them). It seems like most of these methods never use `this` anyway.

In addition, hyperscript uses a lot of string literals (i.e. arguments for `parseElement`). We could make it so that parseElement can accept a `function(parser, runtime, tokens)` and have the grammar elements be top level functions too.

I don't know of automated tools to do this. My method was to read the minified output and look for unchanged names.

**Comment by dz4k** [comment]
Just found out that uglify-js has a `--mangle-props` option that can minify all property names that match some regex. We could prepend our internal methods with some sigil to take advantage of this. (I still think there's value in using as many top-level functions as possible).

**Comment by 1cg** [comment]
I like the --mangle-props idea, maybe explore that?  This doesn't seem worth the savings to me.

**Comment by dz4k** [comment]
> I like the --mangle-props idea, maybe explore that? This doesn't seem worth the savings to me.

The issue with --mangle-props is that almost all of hyperscript's props are exposed (even stuff like `args` and `op`, through the `_hyperscript.internals` api). The methods on _runtime and _parser seem to have no shared state so we could make them top-level functions, but we'd lose the namespacing. I'm starting to see why people use module bundlers now.

**Comment by 1cg** [comment]
closing out as an interesting vein of thought that didn't pan out.

**Pull request closed without merging**
