### PR TITLE
fix(templates): fixed string interpolation in template strings

### PR DESCRIPTION
**Pull request by BirdeeHub**
addresses https://github.com/bigskysoftware/_hyperscript/issues/561

### CODE REVIEW

**Comment by BirdeeHub** [comment]
Edit:

Actually, you still cant escape them...

You couldnt before, but, after this fix you still wont be able to.

Working on a better version now. Hopefully will have in a few days

**Comment by BirdeeHub** [comment]
Ok, well, it escapes properly in all but 1 case now in my local copy that Im working on.

I know what that case is and why it happens, and I could disgustingly fix it but id rather like... nicely fix it.

```js
`test \${x}`
```
currently this case fails still in my local copy.

But Im close. I just need to find a good way to fix the last case

**Comment by BirdeeHub** [comment]
I did have to split up consumeIdentifier and consumeTemplateIdentifier into 2 separate functions though.

Actually, since the current one on here doesnt escape at ALL I will push the updated version in the meantime so you can see where its at.

**Comment by BirdeeHub** [comment]
When I fix the final escaping case:

```js
`test \${x}`
```

This PR will be resubmitted as no longer a draft.

**Comment by BirdeeHub** [comment]
https://github.com/BirdeeHub/_hyperscript/blob/3e29b493e3eb032f5177371218b4f6cf18485c27/src/_hyperscript.js#L279-L286

^ this clause is the one catching that 1 case that I havent addressed yet...

**Comment by BirdeeHub** [comment]
It works now :)

**Comment by 1cg** [comment]
Thank you for this change, did you run the entire test suite against it?

**Comment by BirdeeHub** [comment]
yeah I ran all the tests, I also tried it out in the playground.

I also added the new test which tests many different permutations of the interpolation. In the test I had to double escape because it gets passed through JS first, but in the playground it works as expected, you can escape with `\${}` and it will not interpolate

Also it seems your test suite fails one of the tests when ran via opening with firefox directly but succeeds if you serve with python and then go to the page in the browser? This is unrelated to the new syntax though.

**Pull request merged**
